name: Build, Package and Commit Lambda

on:
  push:
    branches:
      - main
      - master
      - prod
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Read Node.js version from package.json
        id: read_version
        run: |
          NODE_VERSION=$(jq -r '.engines.node' "lambda/package.json")
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        working-directory: lambda
        run: npm install
      - name: Package Lambda function
        working-directory: lambda
        run: zip -r lambda.zip .
      - name: Commit and push lambda.zip
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit and push lambda.zip
          ref: ${{ github.ref_name }} # This refers to the branch being pushed to
