name: Build, Package and Commit Lambda

on:
  push:
    branches:
      - main
      - master
      - prod
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read Node.js version from package.json
        id: read_version
        run: |
          NODE_VERSION=$(jq -r '.engines.node' "lambda/package.json")
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        working-directory: lambda
        run: npm install
      - name: Build Lambda
        working-directory: lambda
        run: npm run build # Customize this step if you have a build step
      - name: Package Lambda function
        working-directory: lambda
        run: zip -r lambda.zip .
      - name: Commit and push lambda.zip
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }} # This refers to the branch being pushed to
          force: false # Optional: force push if needed
          directory: .
          commit_message: Update lambda.zip
